package httpapi

import "github.com/gin-gonic/gin"

func registerLegacyRoutes(router *gin.Engine, s *Server) {
	public := router.Group("/api/public")
	public.GET("/admin-paths", s.legacyAdminPaths)
	public.GET("/payment-region", s.legacyPaymentRegion)
	public.GET("/runtime", s.legacyRuntime)
	public.POST("/subscription/check", s.legacySubscriptionCheck)

	router.POST("/api/admin/login", s.adminLogin)
	router.POST("/api/admin/login/send-tg-code", s.sendTelegramCode)
	router.POST("/api/admin/login/verify-2fa", s.verifyLogin2FA)
	router.POST("/api/verify-cdk", s.legacyVerifyCDK)
	router.GET("/api/cdk/query", s.legacyCDKQuery)
	router.GET("/api/cdk/download", s.legacyProductDownload)
	router.POST("/api/redeem-product", s.claimProduct)
	router.POST("/api/run-process", s.legacyRunProcess)

	admin := router.Group("/api/admin", s.requireAdminSession)
	admin.GET("/session", s.adminSession)
	admin.GET("/security/status", s.legacySecurityStatus)
	admin.GET("/secondary/session", s.secondarySession)
	admin.POST("/verify-secondary", s.verifySecondary)
	admin.POST("/security/2fa-mode", s.legacySave2FAMode)
	admin.POST("/security/paths", s.legacySaveAdminPaths)
	admin.POST("/2fa/setup", s.legacyTOTPSetup)
	admin.POST("/2fa/confirm", s.legacyTOTPConfirm)
	admin.POST("/2fa/disable", s.legacyTOTPDisable)
	admin.POST("/change-password", s.legacyChangePassword)
	admin.POST("/change-secondary-password", s.legacyChangeSecondaryPassword)
	admin.GET("/login-logs", s.legacyLoginLogs)
	admin.GET("/runtime-logs", s.legacyRuntimeLogs)
	admin.POST("/runtime-logs/clear", s.legacyClearRuntimeLogs)
	admin.POST("/proxy/test", s.legacyTestProxyDirect)
	admin.GET("/task-logs", s.legacyTaskLogs)
	admin.DELETE("/task-logs/:jobKey", s.legacyDeleteTaskLog)
	admin.GET("/data", s.legacyAdminData)
	admin.GET("/config", s.getConfig)
	admin.POST("/config", s.legacySaveConfig)
	admin.GET("/card-providers/kimoox/bins", s.legacyKimooxCardBINs)
	admin.POST("/email/test", s.legacyTestEmail)
	admin.GET("/region", s.legacyRegion)
	admin.PUT("/region", s.legacySaveRegion)
	admin.GET("/plans", s.legacyPlans)
	admin.POST("/trigger-activation", s.legacyRunProcess)
	admin.GET("/browser-pool", s.legacyBrowserPool)
	admin.POST("/browser-pool/mode", s.legacyBrowserPoolMode)
	admin.POST("/browser-pool/reload", s.legacyBrowserPoolReload)
	admin.POST("/products/generate", s.generateProducts)
	admin.POST("/products/resume", s.resumeProducts)
	admin.POST("/products/generate-stop", s.stopProducts)
	admin.GET("/products/generation/:jobKey", s.getProductGeneration)
	admin.POST("/subscription/cancel-auto-renew", s.legacySubscriptionAction)
	admin.POST("/subscription/enable-auto-renew", s.legacySubscriptionAction)
	admin.POST("/subscription/batch-renewal-status", s.legacyBatchRenewalStatus)
	admin.GET("/screenshots", s.legacyScreenshots)
	admin.GET("/video", s.legacyVideo)
	admin.GET("/screenshots/:subdir/:filename", s.legacyMedia)

	admin.GET("/gpt-api", s.legacyGPTConfig)
	admin.POST("/gpt-api", s.legacySaveGPTConfig)
	admin.POST("/gpt-api/test", s.legacyTestGPTConfig)
	admin.GET("/gpt-api/status", s.legacyGPTStatus)
	admin.GET("/hcaptcha/logs", s.legacyHcaptchaLogs)
	admin.GET("/hcaptcha", s.legacyHcaptchaConfig)
	admin.POST("/hcaptcha", s.legacySaveHcaptcha)
	admin.POST("/hcaptcha/test", s.legacyTestHcaptcha)
	admin.POST("/hcaptcha/test-vlm", s.legacyTestHcaptchaVLM)
	admin.POST("/hcaptcha/test-captcha-platform", s.legacyTestHcaptchaPlatform)
	admin.GET("/telegram", s.legacyTelegramConfig)
	admin.POST("/telegram", s.legacySaveTelegram)
	admin.POST("/telegram/test", s.legacyTestTelegram)

	admin.GET("/proxies", s.legacyListProxies)
	admin.POST("/proxies", s.legacyAddProxies)
	admin.PUT("/proxies/:id", s.legacyUpdateProxy)
	admin.POST("/proxies/:id/toggle", s.legacyToggleProxy)
	admin.POST("/proxies/:id/test", s.legacyTestProxy)
	admin.POST("/proxies/test-all", s.legacyTestAllProxies)
	admin.DELETE("/proxies/:id", s.legacyDeleteProxy)

	admin.GET("/addresses", s.legacyListAddresses)
	admin.POST("/addresses", s.legacyCreateAddress)
	admin.POST("/addresses/generate-random-us", s.legacyGenerateAddresses)
	admin.DELETE("/addresses/unbound", s.legacyClearAddresses)
	admin.PUT("/addresses/:id", s.legacyUpdateAddress)
	admin.DELETE("/addresses/:id", s.legacyDeleteAddress)

	admin.GET("/billing", s.legacyBilling)
	admin.GET("/billing/export", s.legacyBillingExport)
	admin.GET("/billing/summary/:cardLast4", s.legacyBillingSummary)
	admin.DELETE("/billing/failed", s.legacyDeleteFailedBilling)
	admin.DELETE("/billing/:id", s.legacyDeleteBilling)

	admin.GET("/checkout/plans", s.legacyCheckoutPlans)
	admin.POST("/checkout/generate", s.legacyCheckoutGenerate)
	admin.GET("/checkout/status/:jobKey", s.legacyCheckoutStatus)

	secondary := router.Group("/api/admin", s.requireSecondarySession)
	secondary.GET("/cdks", s.legacyCDKs)
	secondary.POST("/cdks/generate", s.legacyGenerateCDKs)
	secondary.POST("/cdks/import", s.legacyImportCDKs)
	secondary.POST("/cdks/batch/ship", s.legacyShipCDKs)
	secondary.POST("/cdks/batch/delete", s.legacyDeleteCDKs)
	secondary.POST("/cdks/:cdk/ship", s.legacyShipCDK)
	secondary.DELETE("/cdks/:cdk", s.legacyDeleteCDK)
	secondary.GET("/cards", s.legacyCards)
	secondary.POST("/cards/create", s.adminCreateProviderCard)
	secondary.POST("/cards/import", s.legacyImportCards)
	secondary.DELETE("/cards/:id", s.legacyDeleteCard)
	secondary.GET("/card-pools", s.adminCardPools)
	secondary.GET("/sessions", s.legacySessions)
	secondary.GET("/sessions/:jobKey", s.legacySession)
	secondary.GET("/sessions/:jobKey/export", s.legacySessionExport)
	secondary.POST("/sessions/:jobKey/renewal/:action", s.legacySessionRenewalAction)
	registerPoolAssetRoutes(admin, secondary, s)

	router.POST("/api/external/cards/push", s.legacyExternalCardPush)
}
